export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const INIT_APPLICATION = "INIT_APPLICATION";
export const CHANGE_THEME = "CHANGE_THEME";

export const START_LOADDING = "START_LOADDING";
export const END_LOADDING = "END_LOADDING";
